kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: applerole
  tenant: appletenant
  namespace: apple-namespace 
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "delete"]
