kind: Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: futureweirolebinding
  namespace: futurewei-namespace
  tenant: futureweitenant
subjects:
- kind: User
  name: xiaoning 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: futureweirole
  apiGroup: rbac.authorization.k8s.io
