kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: futureweiclusterrolebinding
  tenant: futureweitenant
subjects:
- kind: User
  name: xiaoning 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: futureweiclusterrole
  apiGroup: rbac.authorization.k8s.io
