kind: Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pengdurolebinding
  namespace: default 
  #namespace: pengdunamespace
subjects:
- kind: User
  name: pengdu
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pengdurole
  apiGroup: rbac.authorization.k8s.io
