apiVersion: v1
kind: Pod
metadata:
  name: my-pv-pod
spec:
  volumes:
    - name: my-pv-storage
      persistentVolumeClaim:
        claimName: my-pv-claim
  containers:
    - name: vanilla-container
      image: busybox
      command: ['sh', '-c', 'echo Hello Arktos! && sleep 3600']
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-pv-storage
